### ISSUE TITLE
Unable to Deploy CBS in Azure with TF Provider

### ISSUE THREAD

**Issue by dstamen** [PureStorage-OpenConnect/terraform-provider-cbs#2]
The provider is hard coded to use Purity 6.1.0 and is unable to deploy the new published versions 6.1.2 and 6.1.4

**Comment by ccannon424** [comment]
Released a new version, 0.3.0, that updates the default purity version for the Azure array from 6.1.0 to 6.1.4. Currently working on a long term solution that allows users to specify the Purity version they would like for the array.

**Comment by dstamen** [comment]
This is now possible in 0.6.0
