### ISSUE TITLE
After applied the license_key is not retained

### ISSUE THREAD

**Issue by gwyden** [PureStorage-OpenConnect/terraform-provider-cbs#3]
After a successful application any subsequent plan or apply reports that the license_key needs to be updated in-place. 

-- Deployment --
cbs_array_azure.azure_instance: Still creating... [8m50s elapsed]
cbs_array_azure.azure_instance: Still creating... [9m0s elapsed]
cbs_array_azure.azure_instance: Creation complete after 9m10s [id=/subscriptions/(redacted)/resourceGroups/(redacted)/providers/Microsoft.Solutions/applications/(redacted)]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
-- End deployment --

-- no changes to the deployment but a test of the plan to validate state --
terraform plan
azurerm_resource_group.purecbs-rg: Refreshing state... 
azurerm_resource_group.networking-vnet-ii-rg: Refreshing state... 
cbs_array_azure.azure_instance: Refreshing state...
azurerm_virtual_network.networking-vnet-ii: Refreshing state...

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cbs_array_azure.azure_instance will be updated in-place
  ~ resource "cbs_array_azure" "azure_instance" {
        id                          = "/subscriptions/(redacted)/resourceGroups/(redacted)/providers/Microsoft.Solutions/applications/(redacted)"
      + license_key                 = "<our license key>"
        # (27 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by ps-dbutler** [comment]
Fixed in eb742484fe7c1895feaf0cd16e66daa1dfde1c1b
